import {test,expect} from '@playwright/test';
test('card filters, exact artwork, and leader details work',async({page})=>{
 await page.goto('/');
 await page.getByRole('textbox',{name:'Search cards or sets'}).fill('OP17-001');
 await expect(page.locator('.card-tile')).toHaveCount(1);
 await page.getByRole('button',{name:'View Edward.Newgate OP17-001',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await expect(dialog).toBeVisible();
 await expect(dialog.getByText('Life',{exact:true}).locator('..').locator('strong')).toHaveText('5');
 await expect(dialog.getByText('Cost',{exact:true}).locator('..').locator('strong')).toHaveText('—');
 await expect.poll(()=>dialog.locator('img').evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
 await page.keyboard.press('Escape');
 await expect(dialog).not.toBeVisible();
 await page.getByRole('checkbox',{name:'Show alternate art'}).check();
 await expect(page.locator('.card-tile')).toHaveCount(2);
 await page.getByRole('checkbox',{name:'Show alternate art'}).uncheck();
 await page.getByRole('textbox',{name:'Search cards or sets'}).fill('P-001');
 await expect(page.locator('.card-tile')).toHaveCount(1);
 await expect.poll(()=>page.locator('.card-tile img').evaluate(i=>(i as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
});
test('deck editing, leader exceptions, saving, and import validation work',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Deck builder',exact:true}).click();
 await page.getByLabel('Choose leader',{exact:true}).selectOption('OP15-058');
 await expect(page.getByRole('spinbutton',{name:'DON card count'})).toHaveValue('6');
 await page.getByRole('textbox',{name:'Deck name'}).fill('Playwright crew');
 await page.getByRole('textbox',{name:'Search deck cards'}).fill('OP15-061');
 await page.getByRole('button',{name:/Add .*OP15-061 to deck/}).click();
 await expect(page.locator('.deck-row')).toHaveCount(1);
 await page.getByRole('button',{name:'Save deck',exact:true}).click();
 await expect(page.getByText('Saved in this browser',{exact:true})).toBeVisible();
 await page.reload();await page.getByRole('button',{name:'Deck builder',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Deck name'})).toHaveValue('Playwright crew');
 await expect(page.locator('.deck-row')).toHaveCount(1);
 await page.getByRole('button',{name:'Import',exact:true}).click();
 await page.getByRole('textbox',{name:'Deck list text'}).fill('1 OP99-999');
 await page.getByRole('button',{name:'Import as new deck',exact:true}).click();
 await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Unknown card');
 await page.getByRole('button',{name:'Close deck transfer'}).click();
 await page.getByRole('button',{name:'Export deck',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Deck list text'})).toHaveValue(/1 OP15-058[\s\S]*1 OP15-061[\s\S]*6 DON!!/);
});
test('meta results keep regions separate and source lists load into builder',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Meta & insights',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Read the meta.'})).toBeVisible();
 await expect(page.locator('.results-table tbody tr')).not.toHaveCount(0);
 await expect(page.locator('.results-table tbody')).not.toContainText('JP');
 await page.getByLabel('Meta region').selectOption('Japan');
 await expect(page.locator('.results-table tbody')).toContainText('JP');
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Try a list',exact:true}).first().click();
 await expect(page.getByRole('textbox',{name:'Deck name'})).not.toHaveValue('My next adventure');
 await expect(page.locator('.deck-count-line')).toContainText('50');
});
test('mobile layout has no horizontal overflow and navigation remains usable',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');
 await expect(page.getByRole('heading',{name:'Your next great deck starts here.'})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Open navigation'}).click();
 await page.getByRole('button',{name:'Deck builder',exact:true}).click();
 await expect(page.getByLabel('Choose leader',{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('clearing a leader and replacing an empty edited draft are safe',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Deck builder',exact:true}).click();
 await page.getByLabel('Choose leader',{exact:true}).selectOption('OP15-058');
 await page.getByLabel('Choose leader',{exact:true}).selectOption('');
 await expect(page.getByLabel('Choose leader',{exact:true})).toHaveValue('');
 await expect(page.getByRole('spinbutton',{name:'DON card count'})).toHaveValue('10');
 await page.getByRole('textbox',{name:'Deck name'}).fill('Unsaved empty crew');
 await page.getByRole('button',{name:'Meta & insights',exact:true}).click();
 let warned=false;page.once('dialog',async d=>{warned=true;await d.dismiss();});
 await page.getByRole('button',{name:'Try a list',exact:true}).first().click();
 expect(warned).toBe(true);
 await page.getByRole('button',{name:'Deck builder',exact:true}).click();
 await expect(page.getByRole('textbox',{name:'Deck name'})).toHaveValue('Unsaved empty crew');
});
