import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {selectPokemonEvidence,analyzePokemonDeck} from '../src/pokemon/meta.ts';import {publishPokemonMeta,resolvePokemonList} from '../scripts/import-pokemon-meta.mjs';
const event={id:'a',name:'Regional',date:'2026-09-19',format:'standard',division:'Masters',region:'International',country:'US',player:'Player',placement:'1',archetypeId:'dragapult',sourceUrl:'https://limitlesstcg.com/tournaments/577',list:null} as any;
test('meta excludes wrong division format region and future dates',()=>{const s={checkedAt:'2026-09-27',coverageNotes:'test',guides:[],events:[event,{...event,id:'b',division:'Juniors'},{...event,id:'c',format:'expanded'},{...event,id:'d',region:'Japan'},{...event,id:'e',date:'2026-10-01'}]};assert.deepEqual(selectPokemonEvidence(s,'International','2026-09-01','2026-09-27','').map(e=>e.id),['a']);});
test('unresolved source printing cannot become an importable list',()=>{const cards=[{id:'sv-1',liveCode:'TST',localId:'001',name:'Pikachu'}] as any;assert.equal(resolvePokemonList([{quantity:60,code:'TST',number:'1'}],cards)?.['sv-1'],60);assert.equal(resolvePokemonList([{quantity:59,code:'TST',number:'1'},{quantity:1,code:'MISSING',number:'1'}],cards),null);});
test('bad meta publication preserves previous evidence',async()=>{const dir=await mkdtemp(join(tmpdir(),'pokemon-meta-'));const path=join(dir,'data.json');try{await writeFile(path,'good');await assert.rejects(publishPokemonMeta(path,{events:[{...event,list:{unknown:60}}],guides:[],checkedAt:'2026-09-27'},[]));assert.equal(await readFile(path,'utf8'),'good');}finally{await rm(dir,{recursive:true});}});
test('custom analysis reports missing evolution prerequisites without a fictional score',()=>{const s={checkedAt:'2026-09-27',coverageNotes:'test',events:[],guides:[]};const d={id:'d',name:'custom',cards:{'sv-1':4,'unknown':1}};const a=analyzePokemonDeck(d,[{id:'sv-1',name:'Dragapult ex',category:'Pokemon',stage:'Stage2',evolveFrom:'Drakloak'}] as any,s);assert.ok(a.observations.some(x=>x.includes('Drakloak')));assert.ok(a.observations.some(x=>x.includes('unknown')));assert.equal('score' in a,false);});
test('HTTP-success error pages and incomplete lists cannot replace good evidence',async()=>{
 const {parsePokemonList}=await import('../scripts/import-pokemon-meta.mjs');assert.throws(()=>parsePokemonList('<html><h1>Temporarily unavailable</h1></html>'));
 assert.throws(()=>parsePokemonList('<div class="decklist"><a class="card-link" href="/cards/TST/1"><span class="card-count">59</span></a></div>'));
});
