import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowDownWideNarrow, ArrowRight, Check, ChevronLeft, ChevronRight, ExternalLink, Layers3, Plus, Search, SlidersHorizontal, X } from 'lucide-react';
import type { Card, CatalogSnapshot } from './data.ts';
import { colors, filterCards, setCounts } from './catalog.ts';
import type { CardQuery } from './catalog.ts';
export function CardImage({ card, className = '' }: { card: Card; className?: string }) {
  const [failed, setFailed] = useState(card.artworkAvailable === false);
  useEffect(() => setFailed(card.artworkAvailable === false), [card.imageUrl, card.artworkAvailable]);
  return failed ? <div className={`art-placeholder ${className}`}><Layers3 size={32}/><span>{card.name}</span><small>Artwork unavailable</small></div> : <img className={`card-image ${className}`} src={card.imageUrl} alt={`${card.name} · ${card.number}`} loading="lazy" referrerPolicy="no-referrer" onError={() => setFailed(true)}/>;
}
export function ColorDots({ values }: { values: string[] }) { return <span className="color-dots" aria-label={values.join(' / ')}>{values.map(c => <i key={c} style={{ background: { Red: '#c94c50', Green: '#479a78', Blue: '#5482bd', Purple: '#8f6aaf', Black: '#343b40', Yellow: '#d8b950' }[c] }}/>)}</span>; }
export function CardDetail({ card, cards, onClose, onAdd }: { card: Card; cards: Card[]; onClose: () => void; onAdd: (c: Card) => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  const [selected, setSelected] = useState(card);
  const artworks = cards.filter(c => c.number === card.number);
  useEffect(() => { ref.current?.showModal(); }, []);
  return <dialog ref={ref} className="card-dialog" onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }} aria-labelledby="card-detail-title">
    <button className="icon-button close-dialog" onClick={onClose} aria-label="Close card details"><X size={20}/></button>
    <div className="dialog-art"><CardImage card={selected}/><span>{selected.setCode} · {selected.rarity}</span></div>
    <div className="dialog-info"><p className="eyebrow">{selected.type} / {selected.number}</p><h2 id="card-detail-title">{selected.name}</h2><p><ColorDots values={selected.colors}/> {selected.colors.join(' / ')} · {selected.attribute || 'Attribute unavailable'}</p>
      <div className="detail-stats">{[['Cost', selected.cost], ['Power', selected.power], ['Counter', selected.counter], ['Life', selected.life]].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value ?? '—'}</strong></div>)}</div>
      <h3>Card effect</h3><p className="rules-text">{selected.text && selected.text !== '-' ? selected.text : 'No printed effect.'}</p>{selected.trigger && <p className="rules-text trigger"><strong>Trigger</strong> {selected.trigger}</p>}
      <p className="muted">{selected.traits.join(' / ') || 'Traits unavailable'} · Block {selected.block ?? 'unavailable'}</p>
      <label>Illustration <select value={selected.id} onChange={e => setSelected(artworks.find(c => c.id === e.target.value)!)}>{artworks.map((c, i) => <option key={c.id} value={c.id}>{c.setCode} · Artwork {i + 1}</option>)}</select></label>
      <div className="dialog-actions"><button className="button primary" onClick={() => { onAdd(selected); onClose(); }}><Plus size={16}/>{selected.type === 'LEADER' ? 'Choose as leader' : 'Add to deck'}</button><a className="text-link" href={selected.sourceUrl} target="_blank" rel="noreferrer">Official card <ExternalLink size={14}/></a></div>
    </div>
  </dialog>;
}
const emptyQuery: CardQuery = { search: '', setCode: '', color: '', type: '', rarity: '', cost: '' };
export default function Catalog({ snapshot, onAdd }: { snapshot: CatalogSnapshot; onAdd: (c: Card) => void }) {
  const [query, setQuery] = useState(emptyQuery);
  const [tab, setTab] = useState('cards');
  const [artworks, setArtworks] = useState(false);
  const [sort, setSort] = useState('latest');
  const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<Card | null>(null);
  const setRank = useMemo(() => new Map([...snapshot.sets].sort((a,b) => (a.category === 'Booster' ? 0 : 1) - (b.category === 'Booster' ? 0 : 1) || Number(b.series) - Number(a.series)).map((s,i) => [s.code,i])), [snapshot]);
  const filtered = useMemo(() => {
    let rows = filterCards(snapshot.cards, query);
    if (!artworks) { const seen = new Set<string>(); rows = rows.filter(c => { if (seen.has(c.number)) return false; seen.add(c.number); return true; }); }
    return [...rows].sort((a,b) => sort === 'name' ? a.name.localeCompare(b.name) : sort === 'cost' ? (a.cost ?? 99) - (b.cost ?? 99) : (setRank.get(a.setCode) ?? 0) - (setRank.get(b.setCode) ?? 0) || a.number.localeCompare(b.number));
  }, [snapshot, query, artworks, sort, setRank]);
  const pages = Math.max(1, Math.ceil(filtered.length / 30));
  const update = (key: keyof CardQuery, value: string) => { setQuery(q => ({ ...q, [key]: value })); setPage(1); };
  const latest = snapshot.sets.filter(s => s.category === 'Booster').sort((a,b) => Number(b.series) - Number(a.series))[0];
  const hero = snapshot.cards.filter(c => c.setCode === latest?.code && ['OP17-001', 'OP17-005', 'OP17-118'].includes(c.number)).filter(c => !c.id.includes('_p')).slice(0,3);
  const setList = snapshot.sets.filter(s => `${s.code} ${s.name}`.toLowerCase().includes(query.search.toLowerCase()));
  return <>
    <section className="library-hero"><div className="hero-copy"><p className="eyebrow"><span className="tiny-line"/> THE ONE PIECE CARD GAME, EXPLORED</p><h1>Your next great deck<br/>starts <em>here.</em></h1><p>Every card has a story. Discover yours.<br/>Explore the artwork, find your leader, and build your crew.</p><button className="button primary" onClick={() => { update('setCode', latest?.code ?? ''); document.getElementById('library')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }}>Explore {latest?.code ?? 'the cards'} <ArrowRight size={16}/></button><span className="hero-caption">{latest?.name.replace(/^BOOSTER PACK\s*-/, '').replace(/-?\s*\[.*\]$/, '')}</span></div>
      <div className="hero-art" aria-label="Featured cards from the latest set"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><span className="hero-cross cross-one">+</span><span className="hero-cross cross-two">+</span>{hero.map((c,i) => <button key={c.id} className={`hero-card hero-card-${i}`} onClick={() => setSelected(c)} aria-label={`View featured ${c.name}`}><CardImage card={c}/></button>)}<span className="art-caption">A WORLD OF CARDS.<br/>A DECK THAT'S YOURS.</span></div>
    </section>
    <div className="catalog-stats"><div><strong>{new Set(snapshot.cards.map(c => c.number)).size.toLocaleString()}</strong><span>Unique cards</span></div><div><strong>{snapshot.sets.length}</strong><span>Sets & collections</span></div><div><strong>{snapshot.cards.length.toLocaleString()}</strong><span>Illustrations</span></div><p><Check size={16}/> Official Asia catalog<span>Checked {new Date(snapshot.checkedAt).toLocaleDateString('en-GB', { day:'numeric', month:'short', year:'numeric' })}</span></p></div>
    <section id="library" className="library"><div className="section-heading"><div><p className="eyebrow">FIND YOUR NEXT CARD</p><h2>The card library<span>.</span></h2></div><div className="segmented"><button className={tab === 'cards' ? 'active' : ''} onClick={() => setTab('cards')}><Layers3 size={15}/> All cards</button><button className={tab === 'sets' ? 'active' : ''} onClick={() => setTab('sets')}>Browse sets</button></div></div>
      <div className="filter-toolbar"><label className="search-field"><Search size={17}/><input aria-label="Search cards or sets" placeholder={tab === 'cards' ? 'Search a name, card number, or effect...' : 'Search sets and collections...'} value={query.search} onChange={e => update('search', e.target.value)}/>{query.search && <button className="icon-button" aria-label="Clear search" onClick={() => update('search','')}><X size={14}/></button>}</label>{tab === 'cards' && <><select aria-label="Filter by set" value={query.setCode} onChange={e => update('setCode',e.target.value)}><option value="">All sets</option>{snapshot.sets.map(s => <option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select><select aria-label="Filter by color" value={query.color} onChange={e => update('color',e.target.value)}><option value="">All colors</option>{[...colors, 'Multicolor'].map(c => <option key={c}>{c}</option>)}</select><select aria-label="Filter by type" value={query.type} onChange={e => update('type',e.target.value)}><option value="">All types</option>{['LEADER','CHARACTER','EVENT','STAGE','DON!!'].map(t => <option key={t} value={t}>{t === 'DON!!' ? t : t[0]+t.slice(1).toLowerCase()}</option>)}</select><details className="more-filters"><summary><SlidersHorizontal size={16}/><span>More filters</span></summary><div><label>Rarity<select value={query.rarity} onChange={e => update('rarity',e.target.value)}><option value="">All rarities</option>{['L','C','UC','R','SR','SEC','SP','P'].map(r => <option key={r}>{r}</option>)}</select></label><label>Cost<select value={query.cost} onChange={e => update('cost',e.target.value)}><option value="">All costs</option>{Array.from({length:11},(_,i)=><option key={i}>{i}</option>)}</select></label></div></details></>}</div>
      {tab === 'cards' ? <><div className="results-line"><p aria-live="polite"><strong>{filtered.length.toLocaleString()}</strong> {artworks ? 'illustrations' : 'cards'} to discover{Object.values(query).some(Boolean) && <button className="reset-button" onClick={() => { setQuery(emptyQuery);setPage(1); }}>Reset filters <X size={12}/></button>}</p><div><label className="checkbox-label"><input type="checkbox" checked={artworks} onChange={e => { setArtworks(e.target.checked); setPage(1); }}/> Show alternate art</label><label className="sort-label"><ArrowDownWideNarrow size={16}/><select aria-label="Sort cards" value={sort} onChange={e => {setSort(e.target.value);setPage(1);}}><option value="latest">Newest set</option><option value="name">Name A–Z</option><option value="cost">Lowest cost</option></select></label></div></div>
      {filtered.length ? <div className="card-grid">{filtered.slice((Math.min(page,pages)-1)*30, Math.min(page,pages)*30).map(c => <article className="card-tile" key={c.id}><button className="card-art-button" onClick={() => setSelected(c)} aria-label={`View ${c.name} ${c.number}`}><CardImage card={c}/><span className="card-art-overlay">Explore card <ArrowRight size={15}/></span></button><div className="card-meta"><span>{c.number}</span><span className={`rarity rarity-${c.rarity}`}>{c.rarity}</span></div><button className="card-title" onClick={() => setSelected(c)}>{c.name}</button><div className="card-bottom"><span><ColorDots values={c.colors}/>{c.type === 'DON!!' ? 'DON!!' : c.type[0]+c.type.slice(1).toLowerCase()}</span><button className="add-card" aria-label={`Add ${c.name} ${c.number} to deck`} onClick={() => onAdd(c)}><Plus size={15}/></button></div></article>)}</div> : <div className="empty-state"><Search size={32}/><h3>No cards found</h3><p>Try a different name or clear a filter.</p><button className="button secondary" onClick={() => {setQuery(emptyQuery);setPage(1);}}>Clear filters</button></div>}
      <div className="pagination"><span>Page {Math.min(page,pages)} of {pages}</span><div><button className="button secondary" disabled={page <= 1} onClick={() => setPage(p => p-1)}><ChevronLeft size={16}/> Previous</button><button className="button secondary" disabled={page >= pages} onClick={() => {setPage(p => p+1);document.getElementById('library')?.scrollIntoView({block:'start'});}}>Next <ChevronRight size={16}/></button></div></div></> : <div className="set-grid">{setList.map(s => { const counts=setCounts(snapshot.cards,s.code);const art=snapshot.cards.find(c=>c.setCode===s.code && c.type==='LEADER') ?? snapshot.cards.find(c=>c.setCode===s.code);return <button key={s.code} className="set-tile" onClick={() => {update('setCode',s.code);setTab('cards');}}><div className="set-tile-art">{art && <CardImage card={art}/>}<span>{s.code.startsWith('PROMO') ? 'PROMO' : s.code}</span></div><div className="set-tile-info"><small>{s.category}</small><h3>{s.name.replace(/\s*\[.*\]$/, '')}</h3><p>{counts.uniqueCards} cards · {counts.artworks} illustrations</p><span className="muted">{s.releaseDate ?? 'Release date unverified'}</span><ArrowRight size={18}/></div></button>;})}{!setList.length && <p>No sets match this search.</p>}</div>}
      <p className="coverage-note"><span className="status-dot"/> {snapshot.coverageNotes}</p>
    </section>{selected && <CardDetail key={selected.id} card={selected} cards={snapshot.cards} onClose={() => setSelected(null)} onAdd={onAdd}/>}
  </>;
}
