import { useMemo, useRef, useState } from 'react';
import { AlertCircle, ArrowDownToLine, ArrowRight, Check, Copy, ExternalLink, FileUp, Layers3, Minus, Plus, Save, Search, ShieldCheck, X } from 'lucide-react';
import type { Card, RulesSnapshot } from './data.ts';
import type { Deck } from './deck.ts';
import { exportDeck, parseDeck, validateDeck } from './deck.ts';
import { CardDetail, CardImage, ColorDots } from './Catalog.tsx';
export default function DeckBuilder({ cards, deck, saved, rules, onChange, onSave, onLoad, onNew, dirty, storageError, accountStatus }: { cards: Card[]; deck: Deck; saved: Deck[]; rules: RulesSnapshot; onChange: (d: Deck) => void; onSave: () => void; onLoad: (id: string) => void; onNew: () => void; dirty: boolean; storageError: string; accountStatus?: 'local'|'loading'|'synced'|'pending'|'error'|null }) {
  const [search,setSearch]=useState('');
  const [matching,setMatching]=useState(true);
  const [limit,setLimit]=useState(18);
  const [details,setDetails]=useState<Card|null>(null);
  const [transfer,setTransfer]=useState<'import'|'export'|null>(null);
  const [text,setText]=useState('');
  const [textError,setTextError]=useState('');
  const transferRef=useRef<HTMLDialogElement>(null);
  const index=useMemo(()=>new Map(cards.map(c=>[c.number,c])),[cards]);
  const unique=useMemo(()=>[...index.values()].sort((a,b)=>a.number.localeCompare(b.number)),[index]);
  const leaders=unique.filter(c=>c.type==='LEADER');
  const leader=index.get(deck.leaderNumber??'');
  const validation=validateDeck(deck,cards,rules,new Date().toISOString().slice(0,10));
  const total=Object.values(deck.cards).reduce((a,b)=>a+b,0);
  const pool=unique.filter(c=>['CHARACTER','EVENT','STAGE'].includes(c.type) && (!matching || !leader || c.colors.some(color=>leader.colors.includes(color))) && `${c.name} ${c.number} ${c.text}`.toLowerCase().includes(search.toLowerCase()));
  const entries=Object.entries(deck.cards).sort(([a],[b])=>(index.get(a)?.cost??99)-(index.get(b)?.cost??99)||a.localeCompare(b));
  const chart=Array.from({length:11},(_,cost)=>entries.reduce((n,[number,qty])=>n+(index.get(number)?.cost===cost?qty:0),0));
  const max=Math.max(1,...chart);
  const add=(card:Card,delta=1)=>{
    if(card.type==='LEADER') {onChange({...deck,leaderNumber:card.number,donCount:rules.leaderExceptions[card.number]?.donCount??rules.donCount});return;}
    const next={...deck.cards}; const qty=(next[card.number]??0)+delta;if(qty<1)delete next[card.number];else next[card.number]=qty;
    onChange({...deck,cards:next});
  };
  const openTransfer=(mode:'import'|'export')=>{setTransfer(mode);setText(mode==='export'?exportDeck(deck):'');setTextError('');requestAnimationFrame(()=>transferRef.current?.showModal());};
  const exportFile=()=>{const blob=new Blob([exportDeck(deck)],{type:'text/plain'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${deck.name.replace(/[^a-z0-9]/gi,'-')||'deck'}.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
  return <><div className="page-heading"><div><p className="eyebrow">ONE LEADER. YOUR CREW. YOUR WAY.</p><h1>Build your <em>crew.</em></h1><p>Find the cards that work together. Make the deck your own.</p></div><button className="button secondary" onClick={onNew}><Plus size={15}/> New deck</button></div>
    {storageError&&<div className="alert" role="alert"><AlertCircle size={17}/>{storageError}</div>}
    <div className="deck-workspace"><section className="deck-card-browser"><div className="panel-heading"><h2>Find your crew</h2><span>{pool.length.toLocaleString()} cards</span></div><label className="search-field"><Search size={17}/><input aria-label="Search deck cards" placeholder="Search cards, effects, or card numbers..." value={search} onChange={e=>{setSearch(e.target.value);setLimit(18);}}/></label><div className="deck-pool-filters"><label className="checkbox-label"><input type="checkbox" checked={matching} onChange={e=>{setMatching(e.target.checked);setLimit(18);}}/> Match leader colors</label><span>Click + to add a card</span></div>
      {pool.length?<div className="deck-pool">{pool.slice(0,limit).map(c=><article className="card-tile" key={c.number}><button className="card-art-button" onClick={()=>setDetails(c)} aria-label={`View ${c.name} ${c.number}`}><CardImage card={c}/><span className="card-art-overlay">Card details <ArrowRight size={14}/></span>{deck.cards[c.number]&&<span className="in-deck-count">{deck.cards[c.number]} in deck</span>}</button><div className="card-meta"><span>{c.number}</span><span className="rarity">{c.rarity}</span></div><button className="card-title" onClick={()=>setDetails(c)}>{c.name}</button><div className="card-bottom"><span><ColorDots values={c.colors}/>Cost {c.cost??'—'}</span><button className="add-card" onClick={()=>add(c)} aria-label={`Add ${c.name} ${c.number} to deck`}><Plus size={15}/></button></div></article>)}</div>:<div className="empty-state"><Search size={25}/><p>No cards match. Try another search.</p></div>}{pool.length>limit&&<button className="button secondary load-more" onClick={()=>setLimit(n=>n+18)}>Show more cards</button>}
    </section><aside className="deck-editor"><div className="deck-editor-top"><label className="deck-name-label">DECK NAME<input aria-label="Deck name" value={deck.name} maxLength={80} onChange={e=>onChange({...deck,name:e.target.value})}/></label><span className="save-state">{dirty?'Unsaved changes':accountStatus==='synced'?'Cloud synced':accountStatus?'Saved on this device · pending sync':'Saved in this browser'}</span><div className="deck-save-actions"><button className="button primary" onClick={onSave}><Save size={14}/> Save deck</button><button className="button secondary" onClick={()=>openTransfer('import')}><FileUp size={14}/> Import</button><button className="icon-button" onClick={()=>openTransfer('export')} aria-label="Export deck"><ArrowDownToLine size={18}/></button></div>{saved.length>0&&<label className="saved-deck-select">Your saved decks<select aria-label="Load saved deck" value={saved.some(d=>d.id===deck.id)?deck.id:''} onChange={e=>onLoad(e.target.value)}><option value="" disabled>Choose a saved deck</option>{saved.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}</div>
      <div className="leader-section"><div className="panel-heading"><h3>Your leader</h3><span>1 card</span></div><select aria-label="Choose leader" value={deck.leaderNumber??''} onChange={e=>{const card=index.get(e.target.value);if(card)add(card);else onChange({...deck,leaderNumber:null,donCount:rules.donCount});}}><option value="">Choose your leader…</option>{leaders.map(c=><option key={c.number} value={c.number}>{c.name} · {c.number} · {c.colors.join('/')}</option>)}</select>{leader?<button className="chosen-leader" onClick={()=>setDetails(leader)}><CardImage card={leader}/><span><strong>{leader.name}</strong><small>{leader.number}</small><ColorDots values={leader.colors}/><small>{leader.life??'—'} Life · {leader.power??'—'} Power</small></span><ArrowRight size={16}/></button>:<div className="leader-placeholder"><Layers3 size={22}/><p>Every great crew starts with a leader.</p></div>}</div>
      <div className="deck-count-line"><h3>Main deck</h3><span className={total>50?'over-count':''}><strong>{total}</strong> / {rules.leaderExceptions[deck.leaderNumber??'']?.mainCount??50}</span></div><div className="deck-progress"><span style={{width:`${Math.min(total/50*100,100)}%`}}/></div>
      <div className="deck-list">{entries.length?entries.map(([number,qty])=>{const c=index.get(number);return <div className="deck-row" key={number}>{c?<button onClick={()=>setDetails(c)} className="deck-row-art" aria-label={`Inspect ${c.name}`}><CardImage card={c}/></button>:<Layers3 size={18}/>}<div><strong>{c?.name??number}</strong><span>{number} · Cost {c?.cost??'—'}</span></div><div className="quantity-control"><button onClick={()=>c?add(c,-1):onChange({...deck,cards:Object.fromEntries(entries.filter(([n])=>n!==number))})} aria-label={`Remove one ${number}`}><Minus size={12}/></button><span>{qty}</span><button onClick={()=>c&&add(c)} disabled={!c} aria-label={`Add one ${number}`}><Plus size={12}/></button></div></div>; }):<p className="deck-list-empty">Your crew is waiting to be assembled.<br/>Add cards from the library on the left.</p>}</div>
      <div className="don-section"><span><strong>DON!! deck</strong><small>{rules.leaderExceptions[deck.leaderNumber??'']?.donCount??10} required for this leader</small></span><input type="number" aria-label="DON card count" min="0" max="10" value={deck.donCount} onChange={e=>onChange({...deck,donCount:Number(e.target.value)})}/></div>
      <div className="curve-section"><div className="panel-heading"><h3>Cost curve</h3><span>Printed costs</span></div><div className="cost-chart">{chart.map((qty,i)=><div key={i}><span className="cost-value">{qty||''}</span><div className="cost-bar-track"><span style={{height:`${qty/max*100}%`}}/></div><span>{i===10?'10+':i}</span></div>)}</div></div>
      <div className={`legality-panel ${validation.status}`}><h3><ShieldCheck size={16}/>{validation.status==='invalid'?'Construction needs attention':validation.status==='unverified'?'Construction checked · verify format':'Deck checks passed'}</h3>{validation.issues.length?<ul>{validation.issues.map(issue=><li key={issue}>{issue}</li>)}</ul>:<p>Leader, quantities, colors, and known restrictions pass.</p>}<a className="text-link" href={rules.sourceUrls[1]} target="_blank" rel="noreferrer">Official restrictions <ExternalLink size={12}/></a><small>Checked {new Date(rules.checkedAt).toLocaleDateString('en-GB')} · Asia</small></div>
    </aside></div><div className="builder-note"><ShieldCheck size={17}/><p>{rules.notes[1]}</p></div>
    <dialog ref={transferRef} className="transfer-dialog" onCancel={()=>setTransfer(null)} aria-labelledby="transfer-title"><button className="close-dialog icon-button" onClick={()=>{transferRef.current?.close();setTransfer(null);}} aria-label="Close deck transfer"><X size={18}/></button><p className="eyebrow">TAKE YOUR CREW WITH YOU</p><h2 id="transfer-title">{transfer==='import'?'Import a deck':'Export your deck'}</h2><p>{transfer==='import'?'One card per line: quantity and card number. Include one leader.':'Save this list or copy it into another deck builder.'}</p><label className="transfer-label">Deck list<textarea aria-label="Deck list text" value={text} readOnly={transfer==='export'} placeholder={'1 OP17-001\n4 OP17-002\n10 DON!!'} onChange={e=>setText(e.target.value)} rows={12}/></label>{textError&&<p role="alert" className="form-error">{textError}</p>}<div className="transfer-actions">{transfer==='import'?<button className="button primary" onClick={()=>{try{const d=parseDeck(text,cards);if(dirty&&!window.confirm('Import as a new deck? Unsaved changes in the current draft will be replaced.'))return;onChange(d);transferRef.current?.close();setTransfer(null);}catch(e){setTextError((e as Error).message);}}}><FileUp size={15}/> Import as new deck</button>:<><button className="button primary" onClick={exportFile}><ArrowDownToLine size={15}/> Download .txt</button><button className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(text);setTextError('Copied to clipboard.');}catch{setTextError('Clipboard unavailable. Select the text or download the file.');}}}><Copy size={15}/> Copy list</button></>}</div></dialog>{details&&<CardDetail key={details.id} card={details} cards={cards} onClose={()=>setDetails(null)} onAdd={add}/>}</>;
}
