import { useMemo, useState } from 'react';
import { AlertCircle, ArrowRight, CalendarDays, Check, ChevronDown, ExternalLink, FileUp, Lightbulb, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react';
import type { ArchetypeNote, Card, EventRecord, MetaSnapshot, RulesSnapshot } from './data.ts';
import type { Deck } from './deck.ts';
import { analyzeDeck, selectEvidence } from './meta.ts';
import { CardImage, ColorDots } from './Catalog.tsx';
function Guide({ note }: { note: ArchetypeNote }) {
  return <div className="strategy-guide"><p className="guide-basis"><Lightbulb size={14}/> Qualitative analysis of the printed leader effect. No measured matchup claim.</p><p className="strategy-gameplan">{note.gamePlan}</p><div className="strategy-columns"><div><h4><Check size={14}/> Strengths</h4><ul>{note.strengths.map(s=><li key={s}>{s}</li>)}</ul></div><div><h4><AlertCircle size={14}/> Weaknesses</h4><ul>{note.weaknesses.map(s=><li key={s}>{s}</li>)}</ul></div></div><div className="strategy-suggestions"><h4>Refine your build</h4><ul>{note.suggestions.map(s=><li key={s}>{s}</li>)}</ul></div><div className="guide-sources">{note.sourceUrls.map((url,i)=><a key={url} href={url} target="_blank" rel="noreferrer">Leader effect source {note.sourceUrls.length>1?i+1:''}<ExternalLink size={11}/></a>)}<span>Analysis written {new Date(note.publishedAt).toLocaleDateString('en-GB')}</span></div></div>;
}
export default function Meta({ snapshot, cards, rules, deck, onUseList, onOpenBuilder }: { snapshot: MetaSnapshot; cards: Card[]; rules: RulesSnapshot; deck: Deck; onUseList: (event: EventRecord) => void; onOpenBuilder: () => void }) {
  const [region,setRegion]=useState('Asia');
  const [windowDays,setWindowDays]=useState('30');
  const [country,setCountry]=useState('');
  const [expanded,setExpanded]=useState<string|null>(null);
  const [eventsLimit,setEventsLimit]=useState(10);
  const today=new Date().toISOString().slice(0,10);
  const from=new Date(Date.now()-Number(windowDays)*86400000).toISOString().slice(0,10);
  const index=useMemo(()=>new Map(cards.map(c=>[c.number,c])),[cards]);
  const regional=selectEvidence(snapshot,region,from,today);
  const events=regional.filter(e=>!country || e.country===country);
  const counts=new Map<string,number>();events.forEach(e=>counts.set(e.leaderNumber,(counts.get(e.leaderNumber)??0)+1));
  const ranked=[...counts.entries()].sort((a,b)=>b[1]-a[1]);
  const stale=(Date.now()-Date.parse(snapshot.checkedAt))/86400000>14;
  const analysis=analyzeDeck(deck,cards,snapshot);
  const upcoming=rules.restrictions.filter(r=>r.effectiveFrom>today);
  return <><div className="page-heading meta-heading"><div><p className="eyebrow">KNOW THE FIELD. FIND YOUR EDGE.</p><h1>Read the <em>meta.</em></h1><p>Real tournament lists. Clear trade-offs. Better-informed deck choices.</p></div><span className={`checked-pill ${stale?'stale':''}`}><span className="status-dot"/>{stale?'Snapshot is stale':'Evidence checked'} {new Date(snapshot.checkedAt).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</span></div>
    {upcoming.length>0&&<div className="format-watch"><ShieldCheck size={21}/><div><h3>A change on the horizon</h3><p>{upcoming.map(r=>`${index.get(r.number)?.name??r.number} (${r.number}) ${r.limit===0?'becomes banned':'becomes restricted'} on ${r.effectiveFrom}`).join('. ')}. Results below may reflect the current, pre-change format.</p></div><a href={rules.sourceUrls[1]} target="_blank" rel="noreferrer">Read the notice <ExternalLink size={13}/></a></div>}
    {stale&&<div className="alert" role="status"><AlertCircle size={16}/>This snapshot was checked more than 14 days ago. Refresh evidence before relying on it for current competitive decisions.</div>}
    <div className="meta-filters"><label>Region<select aria-label="Meta region" value={region} onChange={e=>{setRegion(e.target.value);setCountry('');setEventsLimit(10);setExpanded(null);}}><option value="Asia">Asia · excluding Japan</option><option value="Japan">Japan</option></select></label><label>Evidence window<select aria-label="Evidence window" value={windowDays} onChange={e=>{setWindowDays(e.target.value);setCountry('');setEventsLimit(10);}}><option value="14">Last 14 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="365">Last year</option></select></label><label>Country<select aria-label="Meta country" value={country} onChange={e=>{setCountry(e.target.value);setEventsLimit(10);}}><option value="">All countries</option>{[...new Set(regional.map(e=>e.country))].sort().map(c=><option key={c}>{c}</option>)}</select></label><p><CalendarDays size={14}/>{from} — {today}</p></div>
    <div className="meta-summary"><div><span>COLLECTED RESULTS</span><strong>{events.length}</strong><small>Published deck records</small></div><div><span>LEADERS REPRESENTED</span><strong>{counts.size}</strong><small>In this sample</small></div><div><span>REGION</span><strong>{country||region}</strong><small>{region==='Asia'?'Japan is tracked separately':'Japan event records only'}</small></div><div className="sample-disclaimer"><TrendingUp size={24}/><p>A view of the published sample.<br/><strong>Not a global ranking or win rate.</strong></p></div></div>
    <section className="meta-section"><div className="section-heading"><div><p className="eyebrow">WHAT PLAYERS ARE BRINGING</p><h2>Leaders in the field<span>.</span></h2></div><span className="section-caption">Share of {events.length} collected records</span></div>{ranked.length?<div className="archetype-grid">{ranked.slice(0,6).map(([number,count],i)=>{const c=index.get(number);const note=snapshot.archetypes.find(a=>a.leaderNumber===number);const example=events.find(e=>e.leaderNumber===number&&e.list);return <article className="archetype-card" key={number}><div className="archetype-card-top"><div className="archetype-art">{c&&<CardImage card={c}/>}<span>0{i+1}</span></div><div><p className="eyebrow">{note?.style??'Tournament archetype'}</p><h3>{c?.name??number}</h3><p><ColorDots values={c?.colors??[]}/> {number}</p><div className="share-bar"><span style={{width:`${count/events.length*100}%`}}/></div><p className="sample-share"><strong>{(count/events.length*100).toFixed(1)}%</strong> of this sample <span>{count} lists</span></p></div></div><div className="archetype-actions">{note&&<button onClick={()=>setExpanded(expanded===number?null:number)} aria-expanded={expanded===number}><Sparkles size={13}/> Strategy & trade-offs <ChevronDown size={13}/></button>}{example?.list&&<button onClick={()=>onUseList(example)}><FileUp size={13}/> Try a list</button>}{!note&&!example?.list&&<span>Strategy guide not available for this leader yet.</span>}</div>{expanded===number&&note&&<Guide note={note}/>}</article>;})}</div>:<div className="empty-state"><TrendingUp size={32}/><h3>No verified results in this window</h3><p>Choose another region or expand the date range.</p></div>}
      <p className="coverage-note">{snapshot.coverageNotes}</p>
    </section>
    <section className="meta-section results-section"><div className="section-heading"><div><p className="eyebrow">FOLLOW THE EVIDENCE</p><h2>Tournament notebook<span>.</span></h2></div><span className="section-caption">Newest reported results first</span></div>{events.length?<><div className="results-table-wrap"><table className="results-table"><thead><tr><th>Date / location</th><th>Leader / player</th><th>Event</th><th>Result</th><th>Deck list</th></tr></thead><tbody>{events.slice(0,eventsLimit).map(e=><tr key={e.id}><td><strong>{new Date(`${e.date}T00:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</strong><small>{e.country}</small></td><td><strong>{index.get(e.leaderNumber)?.name??e.leaderNumber}</strong><small>{e.player} · {e.leaderNumber}</small></td><td>{e.name}</td><td><span className="placement">{e.placement}</span></td><td><div>{e.list&&<button className="table-import" onClick={()=>onUseList(e)} aria-label={`Load ${e.player}'s ${e.leaderNumber} deck`}><PlusIcon/> Build</button>}<a className="text-link" href={e.sourceUrl} target="_blank" rel="noreferrer" aria-label={`Source for ${e.player}'s ${e.date} result`}><ExternalLink size={14}/></a></div></td></tr>)}</tbody></table></div>{events.length>eventsLimit&&<button className="button secondary load-more" onClick={()=>setEventsLimit(n=>n+10)}>Show more results</button>}</>:<p className="muted no-results-copy">No results match the selected region and dates.</p>}</section>
    <section className="deck-analysis-section"><div className="analysis-intro"><p className="eyebrow">MAKE IT YOUR OWN</p><h2>Your deck, under<br/>the looking glass<span>.</span></h2><p>Structural observations about <strong>{deck.name||'your current deck'}</strong>. These describe your cards, not a simulated matchup.</p><button className="button primary" onClick={onOpenBuilder}>Refine your deck <ArrowRight size={15}/></button></div><div className="analysis-body"><h3><Lightbulb size={17}/> What your list tells us</h3><ul>{analysis.observations.map(s=><li key={s}>{s}</li>)}</ul>{analysis.archetypeNotes?<details className="analysis-guide"><summary>Leader strategy: {analysis.archetypeNotes.title}<ChevronDown size={15}/></summary><Guide note={analysis.archetypeNotes}/></details>:<p className="analysis-unavailable">Detailed archetype guidance isn't available for this leader yet. No matchup score has been inferred.</p>}</div></section>
  </>;
}
function PlusIcon(){return <FileUp size={12}/>;}
